###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

portalAddress: "https://portal.stable.demo.catena-x.net"
portalBackendAddress: "https://portal-backend.stable.demo.catena-x.net"
centralidpAddress: "https://centralidp.stable.demo.catena-x.net"
sharedidpAddress: "https://sharedidp.stable.demo.catena-x.net"
semanticsAddress: "https://semantics.stable.demo.catena-x.net"
dapsAddress: "https://drs.stable.demo.catena-x.net"
bpdmPartnersPoolAddress: "https://partners-pool.stable.demo.catena-x.net"
bpdmPortalGateAddress: "https://portal-gate.stable.demo.catena-x.net"
custodianAddress: "https://managed-identity-wallets.stable.demo.catena-x.net"
sdfactoryAddress: "https://sdfactory.stable.demo.catena-x.net"
clearinghouseAddress: "https://validation.test.dih-cloud.com/api/v1/validation"
clearinghouseTokenAddress: "https://iam.test.dih-cloud.com/realms/carla/protocol/openid-connect/token"

frontend:

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/rewrite-target: "/$1"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.stable.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal.stable.demo.catena-x.net"
    hosts:
      - host: "portal.stable.demo.catena-x.net"
        paths:
          - path: "/(.*)"
            pathType: "Prefix"
            backend:
              service: "portal"
              port: 8080
          - path: "/registration/(.*)"
            pathType: "Prefix"
            backend:
              service: "registration"
              port: 8080
          - path: "/((assets|documentation)/.*)"
            pathType: "Prefix"
            backend:
              service: "assets"
              port: 8080

  portal:
    image:
      portaltag: 1d70aa1bcbf352c77de590a059a6aa19fcdae9c6

  assets:
    image:
      assetstag: efaf6d161cf82da20ccdb89471ff78076dfe3e9c

  registration:
    image:
      registrationtag: 8d79cd5765be80c640101bb288c9c8fe75c9bed4

backend:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/enable-cors: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "8m"
      nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://*.stable.demo.catena-x.net"
    tls:
      - secretName: "tls-secret"
        hosts:
          - "portal-backend.stable.demo.catena-x.net"
    hosts:
      - host: "portal-backend.stable.demo.catena-x.net"
        paths:
          - path: "/api/registration"
            pathType: "Prefix"
            backend:
              service: "registration-service"
              port: 8080
          - path: "/api/administration"
            pathType: "Prefix"
            backend:
              service: "administration-service"
              port: 8080
          - path: "/api/notification"
            pathType: "Prefix"
            backend:
              service: "notification-service"
              port: 8080
          - path: "/api/provisioning"
            pathType: "Prefix"
            backend:
              service: "provisioning-service"
              port: 8080
          - path: "/api/apps"
            pathType: "Prefix"
            backend:
              service: "marketplace-app-service"
              port: 8080
          - path: "/api/services"
            pathType: "Prefix"
            backend:
              service: "services-service"
              port: 8080

  keycloak:
    central:
      clientId: "<path:portal/data/keycloak#central-client-id>"
      clientSecret: "<path:portal/data/stable/keycloak#central-client-secret>"
      dbConnection:
        password: "<path:portal/data/stable/keycloak#central-db-password>"
    shared:
      clientId: "<path:portal/data/keycloak#shared-client-id>"
      clientSecret: "<path:portal/data/stable/keycloak#shared-client-secret>"

  mailing:
    host: "<path:portal/data/mailing#host>"
    port: "<path:portal/data/mailing#port>"
    user: "<path:portal/data/mailing#user>"
    password: "<path:portal/data/mailing#password>"

  registration:
    image:
      registrationservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    logging:
      registrationServiceBpn: "Debug"
    swaggerEnabled: true

  administration:
    image:
      administrationservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    logging:
      businessLogic: "Debug"
      sdfactoryLibrary: "Debug"
    daps:
      clientId: "<path:portal/data/administration#daps-client-id>"
      clientSecret: "<path:portal/data/stable/administration#daps-client-secret>"
    swaggerEnabled: true

  provisioning:
    sharedRealm:
      smtpServer:
        host: "<path:portal/data/mailing#host>"
        port: "<path:portal/data/mailing#port>"
        user: "<path:portal/data/mailing#user>"
        password: "<path:portal/data/mailing#password>"
        from: "<path:portal/data/mailing#from>"
        replyTo: "<path:portal/data/mailing#replyto>"
    service:
      image:
        provisioningservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
      swaggerEnabled: true

  appmarketplace:
    image:
      appmarketplaceservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    logging:
      offersLibrary: "Debug"
    swaggerEnabled: true

  portalmigrations:
    image:
      portalmigrationstag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    seeding:
      testDataEnvironments: "consortia"

  portalmaintenance:
    image:
      portalmaintenancetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1

  notification:
    image:
      notificationservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    swaggerEnabled: true

  services:
    image:
      servicesservicetag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    logging:
      offersLibrary: "Debug"
    swaggerEnabled: true

  provisioningmigrations:
    image:
      provisioningmigrationstag: 8724784f40be5c4d5b3490ba1053000994419ad2

  checklistworker:
    image:
      checklistworkertag: 8ac0de0875563183f32b92ebafa7e67ae76e03d1
    logging:
      checklistLibrary: "Debug"
      bpdmLibrary: "Debug"
      clearinghouseLibrary: "Debug"
      custodianLibrary: "Debug"
      sdfactoryLibrary: "Debug"
    bpdm:
      clientId: "<path:portal/data/checklist-worker#bpdm-client-id>"
      clientSecret: "<path:portal/data/stable/checklist-worker#bpdm-client-secret>"
    clearinghouse:
      clientId: "<path:portal/data/stable/checklist-worker#clearinghouse-client-id>"
      clientSecret: "<path:portal/data/stable/checklist-worker#clearinghouse-client-secret>"
    custodian:
      clientId: "<path:portal/data/checklist-worker#custodian-client-id>"
      clientSecret: "<path:portal/data/stable/checklist-worker#custodian-client-secret>"
    sdfactory:
      issuerBpn: "BPNL00000003CRHK"
      clientId: "<path:portal/data/checklist-worker#sdfactory-client-id>"
      clientSecret: "<path:portal/data/stable/checklist-worker#sdfactory-client-secret>"

postgresql:
  auth:
    password: "<path:portal/data/stable/postgres#postgres-password>"
    replicationPassword: "<path:portal/data/stable/postgres#replication-password>"
    portalPassword: "<path:portal/data/stable/postgres#portal-password>"
    provisioningPassword: "<path:portal/data/stable/postgres#provisioning-password>"
