###############################################################
# Copyright (c) 2021, 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0
###############################################################

name: Portal Release Auto-image-update

on:
  workflow_dispatch:
    inputs:
      new-image:
        description: 'new available image'
        required: true
        default: 'no content'

env:
  IMAGE_BEGINN: 'portaltag: '
  IMAGE_FULL_NEW: 'portaltag: ${{ inputs.new-image }}'

jobs:
  update-image-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Modify image tag in values.yaml
        run: |
          sed -i 's/${{ env.IMAGE_BEGINN }}.*/${{ env.IMAGE_FULL_NEW }}/' charts/portal/values.yaml

      - name: Commit and push updated values.yaml
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/portal/values.yaml
          git commit -m "Add new images for portal"
          bash ./scripts/push.sh
